#!/bin/sh

cargo fmt

# format all json
for file in ./schemas/*/*/*.json; do
  echo "formatting $file"
  jq  '.' "$file" > temp.json && mv temp.json "$file"
done


# format all json
for file in ./schemas/components/*/*/*.json; do
  echo "formatting $file"
  jq  '.' "$file" > temp.json && mv temp.json "$file"
done


for file in ./examples/*.json; do
  echo "formatting $file"
  jq   '.' "$file" > temp.json && mv temp.json "$file"
done

rm temp.json

# create json schema docs
jsonschema2md -d schemas  -o docs/schema -x -

cargo doc --no-deps
rsync -av --delete --exclude 'target' ./target/doc/jacs/ ./docs/jacs/jacs/
cp -R target/doc/static.files/ ./docs/jacs/


# Add the formatted files to the staging area
git add docs/.
git add schemas/.
git add examples/.
git add src/.
git add tests/.
git add benches/.

# Continue with the commit
exit 0
