#!/bin/sh

# Run cargo fmt for all workspace members
cargo fmt --all

# format all json
for file in ./jacs/schemas/*/*/*.json; do
  echo "formatting $file"
  jq  '.' "$file" > temp.json && mv temp.json "$file"
done

# format all json
for file in ./jacs/schemas/components/*/*/*.json; do
  echo "formatting $file"
  jq  '.' "$file" > temp.json && mv temp.json "$file"
done

rm temp.json

# create json schema docs
# todo -r "https://hai.ai/schemas/=schemas/"  or -i schemas fails because of resolving version of json schema
jsonschema2md -d jacs/schemas  -o jacs/docs/schema -x -

mdbook build jacs/docs/jacsbook

# Add the formatted files to the staging area
git add jacs/docs/.
git add jacs/schemas/.
# git add jacs/examples/.
git add jacs/src/.
git add jacs/tests/.
git add jacs/benches/.

# Add workspace members
git add jacs-mcp/src/.
git add jacs-python/src/.

# Add workspace configuration
git add Cargo.toml

# Continue with the commit
exit 0
