/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Hash a string using SHA-256. Sync-only (pure CPU, fast). */
export declare function hashString(data: string): string
/** Create a JACS configuration object. Sync-only (minimal CPU). */
export declare function createConfig(jacsUseSecurity?: string | undefined | null, jacsDataDirectory?: string | undefined | null, jacsKeyDirectory?: string | undefined | null, jacsAgentPrivateKeyFilename?: string | undefined | null, jacsAgentPublicKeyFilename?: string | undefined | null, jacsAgentKeyAlgorithm?: string | undefined | null, jacsPrivateKeyPassword?: string | undefined | null, jacsAgentIdAndVersion?: string | undefined | null, jacsDefaultStorage?: string | undefined | null): string
/** Create a JACS agent programmatically (sync, blocks event loop). */
export declare function createAgentSync(name: string, password: string, algorithm?: string | undefined | null, dataDirectory?: string | undefined | null, keyDirectory?: string | undefined | null, configPath?: string | undefined | null, agentType?: string | undefined | null, description?: string | undefined | null, domain?: string | undefined | null, defaultStorage?: string | undefined | null): string
/** Create a JACS agent programmatically (async, returns Promise). */
export declare function createAgent(name: string, password: string, algorithm?: string | undefined | null, dataDirectory?: string | undefined | null, keyDirectory?: string | undefined | null, configPath?: string | undefined | null, agentType?: string | undefined | null, description?: string | undefined | null, domain?: string | undefined | null, defaultStorage?: string | undefined | null): Promise<string>
/** Add an agent to the local trust store. */
export declare function trustAgent(agentJson: string): string
/** List all trusted agent IDs. */
export declare function listTrustedAgents(): Array<string>
/** Remove an agent from the trust store. */
export declare function untrustAgent(agentId: string): void
/** Check if an agent is in the trust store. */
export declare function isTrusted(agentId: string): boolean
/** Get a trusted agent's JSON document. */
export declare function getTrustedAgent(agentId: string): string
/** Run a security audit (sync, blocks event loop). */
export declare function auditSync(configPath?: string | undefined | null, recentN?: number | undefined | null): string
/** Run a security audit (async, returns Promise). */
export declare function audit(configPath?: string | undefined | null, recentN?: number | undefined | null): Promise<string>
/** @deprecated Use `new JacsAgent()` and `agent.load()` instead. */
export declare function legacyLoad(configPath: string): string
/** @deprecated Use `new JacsAgent()` and instance methods instead. */
export declare function legacySignAgent(agentString: string, publicKey: Buffer, publicKeyEncType: string): string
/** @deprecated Use `new JacsAgent()` and instance methods instead. */
export declare function legacyVerifyString(data: string, signatureBase64: string, publicKey: Buffer, publicKeyEncType: string): boolean
/** @deprecated Use `new JacsAgent()` and instance methods instead. */
export declare function legacySignString(data: string): string
/** @deprecated Use `new JacsAgent()` and instance methods instead. */
export declare function legacyVerifyAgent(agentfile?: string | undefined | null): boolean
/** @deprecated Use `new JacsAgent()` and instance methods instead. */
export declare function legacyUpdateAgent(newAgentString: string): string
/** Result of verify_document_standalone. Exposed to JS as { valid, signerId, timestamp, agentVersion }. */
export interface VerifyStandaloneResult {
  valid: boolean
  /** Signer agent ID; exposed to JS as signerId (camelCase). */
  signerId: string
  /** Signing timestamp from jacsSignature.date. */
  timestamp: string
  /** Signer agent version from jacsSignature.agentVersion. */
  agentVersion: string
}
/**
 * Verify a signed JACS document without loading an agent.
 * Returns { valid, signerId }. Does not use global agent state.
 */
export declare function verifyDocumentStandalone(signedDocument: string, keyResolution?: string | undefined | null, dataDirectory?: string | undefined | null, keyDirectory?: string | undefined | null): VerifyStandaloneResult
/** @deprecated Use `new JacsAgent()` and instance methods instead. */
export declare function legacyVerifyDocument(documentString: string): boolean
/** @deprecated Use `new JacsAgent()` and instance methods instead. */
export declare function legacyUpdateDocument(documentKey: string, newDocumentString: string, attachments?: Array<string> | undefined | null, embed?: boolean | undefined | null): string
/** @deprecated Use `new JacsAgent()` and instance methods instead. */
export declare function legacyVerifySignature(documentString: string, signatureField?: string | undefined | null): boolean
/** @deprecated Use `new JacsAgent()` and instance methods instead. */
export declare function legacyCreateAgreement(documentString: string, agentids: Array<string>, question?: string | undefined | null, context?: string | undefined | null, agreementFieldname?: string | undefined | null): string
/** @deprecated Use `new JacsAgent()` and instance methods instead. */
export declare function legacySignAgreement(documentString: string, agreementFieldname?: string | undefined | null): string
/** @deprecated Use `new JacsAgent()` and instance methods instead. */
export declare function legacyCreateDocument(documentString: string, customSchema?: string | undefined | null, outputfilename?: string | undefined | null, noSave?: boolean | undefined | null, attachments?: string | undefined | null, embed?: boolean | undefined | null): string
/** @deprecated Use `new JacsAgent()` and instance methods instead. */
export declare function legacyCheckAgreement(documentString: string, agreementFieldname?: string | undefined | null): string
/** @deprecated Use `new JacsAgent()` and instance methods instead. */
export declare function legacySignRequest(params: any): string
/** @deprecated Use `new JacsAgent()` and instance methods instead. */
export declare function legacyVerifyResponse(documentString: string): object
/** @deprecated Use `new JacsAgent()` and instance methods instead. */
export declare function legacyVerifyResponseWithAgentId(documentString: string): object
/** Information about a public key fetched from HAI key service. */
export interface RemotePublicKeyInfo {
  /** The raw public key bytes (DER encoded). */
  publicKey: Buffer
  /** The cryptographic algorithm (e.g., "ed25519", "rsa-pss-sha256"). */
  algorithm: string
  /** The hash of the public key (SHA-256). */
  publicKeyHash: string
  /** The agent ID the key belongs to. */
  agentId: string
  /** The version of the key. */
  version: string
}
/** Fetch a public key from HAI's key distribution service. */
export declare function fetchRemoteKey(agentId: string, version?: string | undefined | null): RemotePublicKeyInfo
/** Build a verification URL for a signed JACS document. */
export declare function generateVerifyLink(document: string, baseUrl: string): string
/**
 * JacsAgent is a handle to a JACS agent instance.
 * Each instance maintains its own state and can be used independently.
 * This allows multiple agents to be used concurrently in the same process.
 */
export declare class JacsAgent {
  /**
   * Create a new empty JacsAgent instance.
   * Call `load()` to initialize it with a configuration.
   */
  constructor()
  /** Load an agent from a configuration file (sync, blocks event loop). */
  loadSync(configPath: string): string
  /** Create an ephemeral in-memory agent (sync, blocks event loop). */
  ephemeralSync(algorithm?: string | undefined | null): string
  /** Sign an external agent's document (sync, blocks event loop). */
  signAgentSync(agentString: string, publicKey: Buffer, publicKeyEncType: string): string
  /** Verify a signature on arbitrary string data (sync, blocks event loop). */
  verifyStringSync(data: string, signatureBase64: string, publicKey: Buffer, publicKeyEncType: string): boolean
  /** Sign arbitrary string data (sync, blocks event loop). */
  signStringSync(data: string): string
  /** Verify this agent's signature and hash (sync, blocks event loop). */
  verifyAgentSync(agentfile?: string | undefined | null): boolean
  /** Update the agent document (sync, blocks event loop). */
  updateAgentSync(newAgentString: string): string
  /** Verify a document's signature and hash (sync, blocks event loop). */
  verifyDocumentSync(documentString: string): boolean
  /** Update an existing document (sync, blocks event loop). */
  updateDocumentSync(documentKey: string, newDocumentString: string, attachments?: Array<string> | undefined | null, embed?: boolean | undefined | null): string
  /** Verify a document's signature with optional custom field (sync, blocks event loop). */
  verifySignatureSync(documentString: string, signatureField?: string | undefined | null): boolean
  /** Create an agreement on a document (sync, blocks event loop). */
  createAgreementSync(documentString: string, agentids: Array<string>, question?: string | undefined | null, context?: string | undefined | null, agreementFieldname?: string | undefined | null): string
  /** Create an agreement with extended options (sync, blocks event loop). */
  createAgreementWithOptionsSync(documentString: string, agentids: Array<string>, question?: string | undefined | null, context?: string | undefined | null, agreementFieldname?: string | undefined | null, timeout?: string | undefined | null, quorum?: number | undefined | null, requiredAlgorithms?: Array<string> | undefined | null, minimumStrength?: string | undefined | null): string
  /** Sign an agreement on a document (sync, blocks event loop). */
  signAgreementSync(documentString: string, agreementFieldname?: string | undefined | null): string
  /** Create a new JACS document (sync, blocks event loop). */
  createDocumentSync(documentString: string, customSchema?: string | undefined | null, outputfilename?: string | undefined | null, noSave?: boolean | undefined | null, attachments?: string | undefined | null, embed?: boolean | undefined | null): string
  /** Check an agreement on a document (sync, blocks event loop). */
  checkAgreementSync(documentString: string, agreementFieldname?: string | undefined | null): string
  /** Get setup instructions (sync, blocks event loop). */
  getSetupInstructionsSync(domain: string, ttl?: number | undefined | null): string
  /** Register with HAI.ai (sync, blocks event loop). */
  registerWithHaiSync(apiKey?: string | undefined | null, haiUrl?: string | undefined | null, preview?: boolean | undefined | null): string
  /**
   * Returns diagnostic information as a JSON string.
   * Lightweight — no async variant needed.
   */
  diagnostics(): string
  /** Verify a document by ID (sync, blocks event loop). */
  verifyDocumentByIdSync(documentId: string): boolean
  /** Re-encrypt the agent's private key (sync, blocks event loop). */
  reencryptKeySync(oldPassword: string, newPassword: string): void
  /**
   * Sign a request payload (wraps in a JACS document).
   * Sync-only: uses V8 thread-local JsObject.
   */
  signRequest(params: any): string
  /**
   * Verify a response payload.
   * Sync-only: returns V8 thread-local JsObject.
   */
  verifyResponse(documentString: string): object
  /**
   * Verify a response payload and return the agent ID.
   * Sync-only: returns V8 thread-local JsObject.
   */
  verifyResponseWithAgentId(documentString: string): object
  /** Load an agent from a configuration file. */
  load(configPath: string): Promise<string>
  /** Create an ephemeral in-memory agent. */
  ephemeral(algorithm?: string | undefined | null): Promise<string>
  /** Sign an external agent's document. */
  signAgent(agentString: string, publicKey: Buffer, publicKeyEncType: string): Promise<string>
  /** Verify a signature on arbitrary string data. */
  verifyString(data: string, signatureBase64: string, publicKey: Buffer, publicKeyEncType: string): Promise<boolean>
  /** Sign arbitrary string data with this agent's private key. */
  signString(data: string): Promise<string>
  /** Verify this agent's signature and hash. */
  verifyAgent(agentfile?: string | undefined | null): Promise<boolean>
  /** Update the agent document with new data. */
  updateAgent(newAgentString: string): Promise<string>
  /** Verify a document's signature and hash. */
  verifyDocument(documentString: string): Promise<boolean>
  /** Update an existing document. */
  updateDocument(documentKey: string, newDocumentString: string, attachments?: Array<string> | undefined | null, embed?: boolean | undefined | null): Promise<string>
  /** Verify a document's signature with an optional custom signature field. */
  verifySignature(documentString: string, signatureField?: string | undefined | null): Promise<boolean>
  /** Create an agreement on a document. */
  createAgreement(documentString: string, agentids: Array<string>, question?: string | undefined | null, context?: string | undefined | null, agreementFieldname?: string | undefined | null): Promise<string>
  /** Create an agreement with extended options. */
  createAgreementWithOptions(documentString: string, agentids: Array<string>, question?: string | undefined | null, context?: string | undefined | null, agreementFieldname?: string | undefined | null, timeout?: string | undefined | null, quorum?: number | undefined | null, requiredAlgorithms?: Array<string> | undefined | null, minimumStrength?: string | undefined | null): Promise<string>
  /** Sign an agreement on a document. */
  signAgreement(documentString: string, agreementFieldname?: string | undefined | null): Promise<string>
  /** Create a new JACS document. */
  createDocument(documentString: string, customSchema?: string | undefined | null, outputfilename?: string | undefined | null, noSave?: boolean | undefined | null, attachments?: string | undefined | null, embed?: boolean | undefined | null): Promise<string>
  /** Check an agreement on a document. */
  checkAgreement(documentString: string, agreementFieldname?: string | undefined | null): Promise<string>
  /** Get setup instructions for DNS records, DNSSEC, and HAI registration. */
  getSetupInstructions(domain: string, ttl?: number | undefined | null): Promise<string>
  /** Register this agent with HAI.ai. */
  registerWithHai(apiKey?: string | undefined | null, haiUrl?: string | undefined | null, preview?: boolean | undefined | null): Promise<string>
  /** Verify a document looked up by ID from storage. */
  verifyDocumentById(documentId: string): Promise<boolean>
  /** Re-encrypt the agent's private key with a new password. */
  reencryptKey(oldPassword: string, newPassword: string): Promise<void>
}
