/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Hash a string using SHA-256. */
export declare function hashString(data: string): string
/** Create a JACS configuration object. */
export declare function createConfig(jacsUseSecurity?: string | undefined | null, jacsDataDirectory?: string | undefined | null, jacsKeyDirectory?: string | undefined | null, jacsAgentPrivateKeyFilename?: string | undefined | null, jacsAgentPublicKeyFilename?: string | undefined | null, jacsAgentKeyAlgorithm?: string | undefined | null, jacsPrivateKeyPassword?: string | undefined | null, jacsAgentIdAndVersion?: string | undefined | null, jacsDefaultStorage?: string | undefined | null): string
/** Create a JACS agent programmatically (non-interactive). */
export declare function createAgent(name: string, password: string, algorithm?: string | undefined | null, dataDirectory?: string | undefined | null, keyDirectory?: string | undefined | null, configPath?: string | undefined | null, agentType?: string | undefined | null, description?: string | undefined | null, domain?: string | undefined | null, defaultStorage?: string | undefined | null): string
/** Add an agent to the local trust store. */
export declare function trustAgent(agentJson: string): string
/** List all trusted agent IDs. */
export declare function listTrustedAgents(): Array<string>
/** Remove an agent from the trust store. */
export declare function untrustAgent(agentId: string): void
/** Check if an agent is in the trust store. */
export declare function isTrusted(agentId: string): boolean
/** Get a trusted agent's JSON document. */
export declare function getTrustedAgent(agentId: string): string
/**
 * Run a read-only security audit and health checks.
 * Returns the audit result as a JSON string (risks, health_checks, summary).
 */
export declare function audit(configPath?: string | undefined | null, recentN?: number | undefined | null): string
/** @deprecated Use `new JacsAgent()` and `agent.load()` instead. */
export declare function load(configPath: string): string
/** @deprecated Use `new JacsAgent()` and instance methods instead. */
export declare function signAgent(agentString: string, publicKey: Buffer, publicKeyEncType: string): string
/** @deprecated Use `new JacsAgent()` and instance methods instead. */
export declare function verifyString(data: string, signatureBase64: string, publicKey: Buffer, publicKeyEncType: string): boolean
/** @deprecated Use `new JacsAgent()` and instance methods instead. */
export declare function signString(data: string): string
/** @deprecated Use `new JacsAgent()` and instance methods instead. */
export declare function verifyAgent(agentfile?: string | undefined | null): boolean
/** @deprecated Use `new JacsAgent()` and instance methods instead. */
export declare function updateAgent(newAgentString: string): string
/** Result of verify_document_standalone. Exposed to JS as { valid, signerId }. */
export interface VerifyStandaloneResult {
  valid: boolean
  /** Signer agent ID; exposed to JS as signerId (camelCase). */
  signerId: string
}
/**
 * Verify a signed JACS document without loading an agent.
 * Returns { valid, signerId }. Does not use global agent state.
 */
export declare function verifyDocumentStandalone(signedDocument: string, keyResolution?: string | undefined | null, dataDirectory?: string | undefined | null, keyDirectory?: string | undefined | null): VerifyStandaloneResult
/** @deprecated Use `new JacsAgent()` and instance methods instead. */
export declare function verifyDocument(documentString: string): boolean
/** @deprecated Use `new JacsAgent()` and instance methods instead. */
export declare function updateDocument(documentKey: string, newDocumentString: string, attachments?: Array<string> | undefined | null, embed?: boolean | undefined | null): string
/** @deprecated Use `new JacsAgent()` and instance methods instead. */
export declare function verifySignature(documentString: string, signatureField?: string | undefined | null): boolean
/** @deprecated Use `new JacsAgent()` and instance methods instead. */
export declare function createAgreement(documentString: string, agentids: Array<string>, question?: string | undefined | null, context?: string | undefined | null, agreementFieldname?: string | undefined | null): string
/** @deprecated Use `new JacsAgent()` and instance methods instead. */
export declare function signAgreement(documentString: string, agreementFieldname?: string | undefined | null): string
/** @deprecated Use `new JacsAgent()` and instance methods instead. */
export declare function createDocument(documentString: string, customSchema?: string | undefined | null, outputfilename?: string | undefined | null, noSave?: boolean | undefined | null, attachments?: string | undefined | null, embed?: boolean | undefined | null): string
/** @deprecated Use `new JacsAgent()` and instance methods instead. */
export declare function checkAgreement(documentString: string, agreementFieldname?: string | undefined | null): string
/** @deprecated Use `new JacsAgent()` and instance methods instead. */
export declare function signRequest(params: any): string
/** @deprecated Use `new JacsAgent()` and instance methods instead. */
export declare function verifyResponse(documentString: string): object
/** @deprecated Use `new JacsAgent()` and instance methods instead. */
export declare function verifyResponseWithAgentId(documentString: string): object
/**
 * Information about a public key fetched from HAI key service.
 *
 * This struct contains the public key data and metadata returned by
 * the HAI key distribution service.
 */
export interface RemotePublicKeyInfo {
  /** The raw public key bytes (DER encoded). */
  publicKey: Buffer
  /** The cryptographic algorithm (e.g., "ed25519", "rsa-pss-sha256"). */
  algorithm: string
  /** The hash of the public key (SHA-256). */
  publicKeyHash: string
  /** The agent ID the key belongs to. */
  agentId: string
  /** The version of the key. */
  version: string
}
/**
 * Fetch a public key from HAI's key distribution service.
 *
 * This function retrieves the public key for a specific agent and version
 * from the HAI key distribution service. It is used to obtain trusted public
 * keys for verifying agent signatures without requiring local key storage.
 *
 * # Arguments
 *
 * * `agent_id` - The unique identifier of the agent whose key to fetch.
 * * `version` - The version of the agent's key to fetch. Use "latest" for
 *   the most recent version. If not provided, defaults to "latest".
 *
 * # Returns
 *
 * Returns a `RemotePublicKeyInfo` object containing the public key, algorithm, and hash.
 *
 * # Environment Variables
 *
 * * `HAI_KEYS_BASE_URL` - Base URL for the key service. Defaults to `https://keys.hai.ai`.
 *
 * # Example
 *
 * ```javascript
 * const { fetchRemoteKey } = require('@hai.ai/jacs');
 *
 * const keyInfo = fetchRemoteKey('550e8400-e29b-41d4-a716-446655440000', 'latest');
 * console.log('Algorithm:', keyInfo.algorithm);
 * console.log('Hash:', keyInfo.publicKeyHash);
 * ```
 */
export declare function fetchRemoteKey(agentId: string, version?: string | undefined | null): RemotePublicKeyInfo
/**
 * Build a verification URL for a signed JACS document.
 *
 * Encodes `document` as URL-safe base64 (no padding) and returns a full URL
 * like `https://hai.ai/jacs/verify?s=...`. Throws if the URL would exceed 2048 chars.
 */
export declare function generateVerifyLink(document: string, baseUrl: string): string
/**
 * JacsAgent is a handle to a JACS agent instance.
 * Each instance maintains its own state and can be used independently.
 * This allows multiple agents to be used concurrently in the same process.
 */
export declare class JacsAgent {
  /**
   * Create a new empty JacsAgent instance.
   * Call `load()` to initialize it with a configuration.
   */
  constructor()
  /** Load an agent from a configuration file. */
  load(configPath: string): string
  /**
   * Create an ephemeral in-memory agent. No config, no files, no env vars needed.
   *
   * Replaces this instance's inner agent with a freshly created ephemeral agent
   * that lives entirely in memory. Returns a JSON string with agent info
   * (agent_id, name, version, algorithm).
   */
  ephemeral(algorithm?: string | undefined | null): string
  /** Sign an external agent's document with this agent's registration signature. */
  signAgent(agentString: string, publicKey: Buffer, publicKeyEncType: string): string
  /** Verify a signature on arbitrary string data. */
  verifyString(data: string, signatureBase64: string, publicKey: Buffer, publicKeyEncType: string): boolean
  /** Sign arbitrary string data with this agent's private key. */
  signString(data: string): string
  /** Verify this agent's signature and hash. */
  verifyAgent(agentfile?: string | undefined | null): boolean
  /** Update the agent document with new data. */
  updateAgent(newAgentString: string): string
  /** Verify a document's signature and hash. */
  verifyDocument(documentString: string): boolean
  /** Update an existing document. */
  updateDocument(documentKey: string, newDocumentString: string, attachments?: Array<string> | undefined | null, embed?: boolean | undefined | null): string
  /** Verify a document's signature with an optional custom signature field. */
  verifySignature(documentString: string, signatureField?: string | undefined | null): boolean
  /** Create an agreement on a document. */
  createAgreement(documentString: string, agentids: Array<string>, question?: string | undefined | null, context?: string | undefined | null, agreementFieldname?: string | undefined | null): string
  /** Create an agreement with extended options (timeout, quorum, algorithm constraints). */
  createAgreementWithOptions(documentString: string, agentids: Array<string>, question?: string | undefined | null, context?: string | undefined | null, agreementFieldname?: string | undefined | null, timeout?: string | undefined | null, quorum?: number | undefined | null, requiredAlgorithms?: Array<string> | undefined | null, minimumStrength?: string | undefined | null): string
  /** Sign an agreement on a document. */
  signAgreement(documentString: string, agreementFieldname?: string | undefined | null): string
  /** Create a new JACS document. */
  createDocument(documentString: string, customSchema?: string | undefined | null, outputfilename?: string | undefined | null, noSave?: boolean | undefined | null, attachments?: string | undefined | null, embed?: boolean | undefined | null): string
  /** Check an agreement on a document. */
  checkAgreement(documentString: string, agreementFieldname?: string | undefined | null): string
  /**
   * Get setup instructions for publishing DNS records, DNSSEC, and HAI registration.
   * Returns a JSON string with dns_record_bind, provider_commands, dnssec_instructions, etc.
   */
  getSetupInstructions(domain: string, ttl?: number | undefined | null): string
  /**
   * Register this agent with HAI.ai.
   * Returns a JSON string with hai_registered, hai_error, dns_record, dns_route53.
   */
  registerWithHai(apiKey?: string | undefined | null, haiUrl?: string | undefined | null, preview?: boolean | undefined | null): string
  /** Returns diagnostic information as a JSON string. */
  diagnostics(): string
  /**
   * Verify a document looked up by ID from storage.
   *
   * The document_id should be in "uuid:version" format.
   */
  verifyDocumentById(documentId: string): boolean
  /** Re-encrypt the agent's private key with a new password. */
  reencryptKey(oldPassword: string, newPassword: string): void
  /** Sign a request payload (wraps in a JACS document). */
  signRequest(params: any): string
  /** Verify a response payload. */
  verifyResponse(documentString: string): object
  /** Verify a response payload and return the agent ID. */
  verifyResponseWithAgentId(documentString: string): object
}
