/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const { existsSync, readFileSync } = require('fs')
const { join } = require('path')

const { platform, arch } = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

function isMusl() {
  // For Node 10
  if (!process.report || typeof process.report.getReport !== 'function') {
    try {
      const lddPath = require('child_process').execSync('which ldd').toString().trim()
      return readFileSync(lddPath, 'utf8').includes('musl')
    } catch (e) {
      return true
    }
  } else {
    const { glibcVersionRuntime } = process.report.getReport().header
    return !glibcVersionRuntime
  }
}

switch (platform) {
  case 'android':
    switch (arch) {
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'jacs.android-arm64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./jacs.android-arm64.node')
          } else {
            nativeBinding = require('@hai.ai/jacs-android-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm':
        localFileExisted = existsSync(join(__dirname, 'jacs.android-arm-eabi.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./jacs.android-arm-eabi.node')
          } else {
            nativeBinding = require('@hai.ai/jacs-android-arm-eabi')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Android ${arch}`)
    }
    break
  case 'win32':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(
          join(__dirname, 'jacs.win32-x64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./jacs.win32-x64-msvc.node')
          } else {
            nativeBinding = require('@hai.ai/jacs-win32-x64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'ia32':
        localFileExisted = existsSync(
          join(__dirname, 'jacs.win32-ia32-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./jacs.win32-ia32-msvc.node')
          } else {
            nativeBinding = require('@hai.ai/jacs-win32-ia32-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'jacs.win32-arm64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./jacs.win32-arm64-msvc.node')
          } else {
            nativeBinding = require('@hai.ai/jacs-win32-arm64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Windows: ${arch}`)
    }
    break
  case 'darwin':
    localFileExisted = existsSync(join(__dirname, 'jacs.darwin-universal.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./jacs.darwin-universal.node')
      } else {
        nativeBinding = require('@hai.ai/jacs-darwin-universal')
      }
      break
    } catch {}
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'jacs.darwin-x64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./jacs.darwin-x64.node')
          } else {
            nativeBinding = require('@hai.ai/jacs-darwin-x64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'jacs.darwin-arm64.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./jacs.darwin-arm64.node')
          } else {
            nativeBinding = require('@hai.ai/jacs-darwin-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on macOS: ${arch}`)
    }
    break
  case 'freebsd':
    if (arch !== 'x64') {
      throw new Error(`Unsupported architecture on FreeBSD: ${arch}`)
    }
    localFileExisted = existsSync(join(__dirname, 'jacs.freebsd-x64.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./jacs.freebsd-x64.node')
      } else {
        nativeBinding = require('@hai.ai/jacs-freebsd-x64')
      }
    } catch (e) {
      loadError = e
    }
    break
  case 'linux':
    switch (arch) {
      case 'x64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'jacs.linux-x64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./jacs.linux-x64-musl.node')
            } else {
              nativeBinding = require('@hai.ai/jacs-linux-x64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'jacs.linux-x64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./jacs.linux-x64-gnu.node')
            } else {
              nativeBinding = require('@hai.ai/jacs-linux-x64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'jacs.linux-arm64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./jacs.linux-arm64-musl.node')
            } else {
              nativeBinding = require('@hai.ai/jacs-linux-arm64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'jacs.linux-arm64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./jacs.linux-arm64-gnu.node')
            } else {
              nativeBinding = require('@hai.ai/jacs-linux-arm64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'jacs.linux-arm-musleabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./jacs.linux-arm-musleabihf.node')
            } else {
              nativeBinding = require('@hai.ai/jacs-linux-arm-musleabihf')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'jacs.linux-arm-gnueabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./jacs.linux-arm-gnueabihf.node')
            } else {
              nativeBinding = require('@hai.ai/jacs-linux-arm-gnueabihf')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'riscv64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'jacs.linux-riscv64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./jacs.linux-riscv64-musl.node')
            } else {
              nativeBinding = require('@hai.ai/jacs-linux-riscv64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'jacs.linux-riscv64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./jacs.linux-riscv64-gnu.node')
            } else {
              nativeBinding = require('@hai.ai/jacs-linux-riscv64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 's390x':
        localFileExisted = existsSync(
          join(__dirname, 'jacs.linux-s390x-gnu.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./jacs.linux-s390x-gnu.node')
          } else {
            nativeBinding = require('@hai.ai/jacs-linux-s390x-gnu')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`)
    }
    break
  default:
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`)
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError
  }
  throw new Error(`Failed to load native binding`)
}

const { JacsAgent, hashString, createConfig, createAgent, trustAgent, listTrustedAgents, untrustAgent, isTrusted, getTrustedAgent, audit, load, signAgent, verifyString, signString, verifyAgent, updateAgent, verifyDocumentStandalone, verifyDocument, updateDocument, verifySignature, createAgreement, signAgreement, createDocument, checkAgreement, signRequest, verifyResponse, verifyResponseWithAgentId, fetchRemoteKey, generateVerifyLink } = nativeBinding

module.exports.JacsAgent = JacsAgent
module.exports.hashString = hashString
module.exports.createConfig = createConfig
module.exports.createAgent = createAgent
module.exports.trustAgent = trustAgent
module.exports.listTrustedAgents = listTrustedAgents
module.exports.untrustAgent = untrustAgent
module.exports.isTrusted = isTrusted
module.exports.getTrustedAgent = getTrustedAgent
module.exports.audit = audit
module.exports.load = load
module.exports.signAgent = signAgent
module.exports.verifyString = verifyString
module.exports.signString = signString
module.exports.verifyAgent = verifyAgent
module.exports.updateAgent = updateAgent
module.exports.verifyDocumentStandalone = verifyDocumentStandalone
module.exports.verifyDocument = verifyDocument
module.exports.updateDocument = updateDocument
module.exports.verifySignature = verifySignature
module.exports.createAgreement = createAgreement
module.exports.signAgreement = signAgreement
module.exports.createDocument = createDocument
module.exports.checkAgreement = checkAgreement
module.exports.signRequest = signRequest
module.exports.verifyResponse = verifyResponse
module.exports.verifyResponseWithAgentId = verifyResponseWithAgentId
module.exports.fetchRemoteKey = fetchRemoteKey
module.exports.generateVerifyLink = generateVerifyLink
