# Generated by scripts/homebrew_release.py from attested CLI release assets.
class Jacs < Formula
  desc "Portable signed JSON and verify-only MCP server"
  homepage "https://github.com/HumanAssisted/JACS"
  version "0.15.0"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/HumanAssisted/JACS/releases/download/cli/v0.15.0/jacs-cli-0.15.0-darwin-arm64.tar.gz"
      sha256 "b02a1f24da4b68ce2eac0e13f876ce31049b9de5ac7f3120bed7820422fbdbd3"
    end
    on_intel do
      url "https://github.com/HumanAssisted/JACS/releases/download/cli/v0.15.0/jacs-cli-0.15.0-darwin-x64.tar.gz"
      sha256 "9397bb61d19ee5f9b1ddd271137c6e502b37da62ec048f67df7d1a0b48726e45"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/HumanAssisted/JACS/releases/download/cli/v0.15.0/jacs-cli-0.15.0-linux-arm64.tar.gz"
      sha256 "34cbd1501ccfbdbbc562b51b3c9a1d22098ffa2deedd7b41a73dd9ef22bb5be9"
    end
    on_intel do
      url "https://github.com/HumanAssisted/JACS/releases/download/cli/v0.15.0/jacs-cli-0.15.0-linux-x64.tar.gz"
      sha256 "7c122ec1d6d06a7335c4a33688e9da9225750966d23c5c3f8e8244cc4c611e22"
    end
  end

  def install
    bin.install "jacs-cli" => "jacs"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/jacs --version")
    assert_match "mcp", shell_output("#{bin}/jacs --help")
    assert_match "verify-only", shell_output("#{bin}/jacs mcp --help")
  end
end
