//! Wave 2 / Task 005: golden-byte canonicalization tests.
//!
//! The 10 sample inputs were locked in Wave 0 (Task 001). Their canonical
//! outputs were generated by `jacs::protocol::canonicalize_json` (which is
//! now a re-export of `jacs_core::canonical::canonicalize_json`). Any drift
//! between the two is a wire-incompatibility release blocker.

use serde_json::Value;

#[derive(serde::Deserialize)]
struct Sample {
    name: String,
    data: Value,
}

#[test]
fn canonicalize_json_in_jacs_core_matches_goldens() {
    let inputs: Vec<Sample> =
        serde_json::from_str(include_str!("fixtures/wasm_compat/canonical_inputs.json"))
            .expect("canonical_inputs.json parses");
    let outputs: std::collections::HashMap<String, String> =
        serde_json::from_str(include_str!("fixtures/wasm_compat/canonical_outputs.json"))
            .expect("canonical_outputs.json parses");

    assert_eq!(inputs.len(), 10, "expected 10 sample inputs per PRD");
    assert_eq!(
        outputs.len(),
        10,
        "expected 10 golden outputs to match inputs"
    );

    for sample in inputs {
        let actual = jacs_core::canonical::canonicalize_json(&sample.data);
        let expected = outputs
            .get(&sample.name)
            .unwrap_or_else(|| panic!("no golden for {}", sample.name));
        assert_eq!(
            &actual, expected,
            "canonical bytes drift for {}: got {:?}, expected {:?}",
            sample.name, actual, expected
        );
    }
}

#[test]
fn canonicalize_json_try_returns_same_bytes_as_infallible() {
    let v = serde_json::json!({"b": 1, "a": 2, "nested": {"z": 3, "y": 4}});
    let infallible = jacs_core::canonical::canonicalize_json(&v);
    let fallible =
        jacs_core::canonical::canonicalize_json_try(&v).expect("infallible for valid JSON");
    assert_eq!(infallible, fallible);
}
