/**
 * Cross-language attestation verification tests for JACS Node.js bindings.
 *
 * Verifies that attestation documents created by the Rust core can be verified
 * by Node.js bindings, and that Node.js can read attestation structures across
 * both Ed25519 and pq2025 algorithms.
 *
 * Fixture directory: jacs/tests/fixtures/cross-language/attestation/
 * Generated by: jacs/tests/attestation_cross_lang_tests.rs
 */

const { expect } = require('chai');
const path = require('path');
const fs = require('fs');

let simple;
try {
  simple = require('../simple.js');
} catch (e) {
  simple = null;
}

let clientModule;
try {
  clientModule = require('../client.js');
} catch (e) {
  clientModule = null;
}

// Check if attestation feature is available
let hasAttestation = false;
if (clientModule) {
  try {
    const probe = clientModule.JacsClient.ephemeralSync('ring-Ed25519');
    hasAttestation = typeof probe.createAttestation === 'function';
  } catch (_) {}
}

const WORKSPACE_ROOT = path.resolve(__dirname, '../..');
const FIXTURES_DIR = path.join(
  WORKSPACE_ROOT,
  'jacs',
  'tests',
  'fixtures',
  'cross-language',
  'attestation',
);
const IAT_SKEW_ENV_VAR = 'JACS_MAX_IAT_SKEW_SECONDS';

const ALGORITHMS = [
  { prefix: 'ed25519', name: 'Ed25519', nodeAlgo: 'ring-Ed25519' },
  { prefix: 'pq2025', name: 'pq2025', nodeAlgo: 'pq2025' },
];

function fixtureExists(prefix) {
  return (
    fs.existsSync(path.join(FIXTURES_DIR, `${prefix}_attestation.json`)) &&
    fs.existsSync(path.join(FIXTURES_DIR, `${prefix}_metadata.json`)) &&
    fs.existsSync(path.join(FIXTURES_DIR, `${prefix}_public_key.pem`))
  );
}

function readFixture(prefix) {
  const attestationPath = path.join(FIXTURES_DIR, `${prefix}_attestation.json`);
  const metadataPath = path.join(FIXTURES_DIR, `${prefix}_metadata.json`);
  return {
    attestation: fs.readFileSync(attestationPath, 'utf8'),
    metadata: JSON.parse(fs.readFileSync(metadataPath, 'utf8')),
  };
}

// Build a standalone key cache from fixture public keys
function buildStandaloneKeyCache() {
  const varDir = path.join(WORKSPACE_ROOT, 'jacsnpm', 'var');
  fs.mkdirSync(varDir, { recursive: true });
  const cacheDir = path.join(
    varDir,
    `att-cross-lang-key-cache-${process.pid}-${Date.now()}`,
  );
  fs.mkdirSync(cacheDir, { recursive: true });
  const publicKeysDir = path.join(cacheDir, 'public_keys');
  fs.mkdirSync(publicKeysDir, { recursive: true });

  for (const algo of ALGORITHMS) {
    if (!fixtureExists(algo.prefix)) continue;
    const { metadata } = readFixture(algo.prefix);
    const rawKeyPath = path.join(FIXTURES_DIR, `${algo.prefix}_public_key.pem`);
    const keyHash = metadata.public_key_hash;
    const signingAlgorithm = metadata.signing_algorithm;
    if (!keyHash || !signingAlgorithm || !fs.existsSync(rawKeyPath)) continue;

    const keyBytes = fs.readFileSync(rawKeyPath);
    fs.writeFileSync(path.join(publicKeysDir, `${keyHash}.pem`), keyBytes);
    fs.writeFileSync(
      path.join(publicKeysDir, `${keyHash}.enc_type`),
      signingAlgorithm,
    );
  }

  return cacheDir;
}

describe('Cross-language attestation verification', function () {
  this.timeout(30000);

  const available = simple !== null;
  const fixturesDirExists = fs.existsSync(FIXTURES_DIR);
  let STANDALONE_CACHE_DIR = null;
  let previousIatSkewEnv = undefined;

  before(function () {
    if (!available) {
      console.log('  Skipping attestation cross-language tests - simple.js not compiled');
      this.skip();
    }
    if (!fixturesDirExists) {
      console.log('  Skipping attestation cross-language tests - fixtures directory not found');
      this.skip();
    }
    previousIatSkewEnv = process.env[IAT_SKEW_ENV_VAR];
    process.env[IAT_SKEW_ENV_VAR] = '0';
    STANDALONE_CACHE_DIR = buildStandaloneKeyCache();
  });

  after(function () {
    if (STANDALONE_CACHE_DIR) {
      fs.rmSync(STANDALONE_CACHE_DIR, { recursive: true, force: true });
      STANDALONE_CACHE_DIR = null;
    }
    if (previousIatSkewEnv === undefined) {
      delete process.env[IAT_SKEW_ENV_VAR];
    } else {
      process.env[IAT_SKEW_ENV_VAR] = previousIatSkewEnv;
    }
  });

  function standaloneOpts() {
    const rel = path.relative(process.cwd(), STANDALONE_CACHE_DIR);
    return { keyResolution: 'local', dataDirectory: rel || '.', keyDirectory: rel || '.' };
  }

  // ---------------------------------------------------------------------------
  // Per-algorithm: verify Rust-generated attestation fixtures
  // ---------------------------------------------------------------------------

  for (const algo of ALGORITHMS) {
    describe(`${algo.name} attestation (${algo.prefix})`, () => {
      const hasFixture = fixturesDirExists && fixtureExists(algo.prefix);

      (available && hasFixture ? it : it.skip)(
        'should verify a Rust-generated attestation with verifyStandalone',
        () => {
          const { attestation, metadata } = readFixture(algo.prefix);

          const result = simple.verifyStandalone(attestation, standaloneOpts());

          expect(result).to.be.an('object');
          expect(result.valid).to.equal(
            true,
            `Failed to verify ${algo.name} attestation`,
          );
          expect(result.signerId).to.equal(
            metadata.agent_id,
            `Signer ID should match metadata for ${algo.name}`,
          );
        },
      );

      (available && hasFixture ? it : it.skip)(
        'should have valid attestation document structure',
        () => {
          const { attestation } = readFixture(algo.prefix);
          const doc = JSON.parse(attestation);

          // JACS fields
          expect(doc).to.have.property('jacsId');
          expect(doc).to.have.property('jacsVersion');
          expect(doc).to.have.property('jacsSignature');
          expect(doc).to.have.property('jacsSha256');

          // Attestation fields
          expect(doc).to.have.property('attestation');
          expect(doc.attestation).to.have.property('subject');
          expect(doc.attestation.subject).to.have.property('id', 'cross-lang-artifact-001');
          expect(doc.attestation.subject).to.have.property('type', 'artifact');
          expect(doc.attestation.subject).to.have.property('digests');
          expect(doc.attestation.subject.digests).to.have.property('sha256');

          // Claims
          expect(doc.attestation).to.have.property('claims').that.is.an('array');
          expect(doc.attestation.claims.length).to.be.greaterThan(0);
          expect(doc.attestation.claims[0]).to.have.property('name', 'reviewed');
          expect(doc.attestation.claims[0]).to.have.property('value', true);
          expect(doc.attestation.claims[0]).to.have.property('confidence', 0.95);

          // Evidence
          expect(doc.attestation).to.have.property('evidence').that.is.an('array');
          expect(doc.attestation.evidence.length).to.be.greaterThan(0);
        },
      );

      (available && hasFixture ? it : it.skip)(
        'should reject a tampered attestation',
        () => {
          const { attestation } = readFixture(algo.prefix);
          const doc = JSON.parse(attestation);
          // Tamper with attestation body
          doc.attestation.subject.id = 'tampered-id';
          const tamperedJson = JSON.stringify(doc);

          const result = simple.verifyStandalone(tamperedJson, standaloneOpts());
          expect(result.valid).to.equal(
            false,
            `Tampered ${algo.name} attestation should not verify`,
          );
        },
      );

      (available && hasFixture ? it : it.skip)(
        'should have correct signing metadata',
        () => {
          const { attestation, metadata } = readFixture(algo.prefix);
          const doc = JSON.parse(attestation);

          expect(doc.jacsSignature.agentID).to.equal(metadata.agent_id);
          expect(doc.jacsSignature.signingAlgorithm).to.equal(metadata.signing_algorithm);
          expect(doc.jacsSignature).to.have.property('publicKeyHash');
          expect(doc.jacsSignature.publicKeyHash).to.equal(metadata.public_key_hash);
        },
      );
    });
  }

  // ---------------------------------------------------------------------------
  // Node.js creates attestation from Rust fixture content (if attestation available)
  // ---------------------------------------------------------------------------

  describe('Node.js attestation creation from Rust fixture data', () => {
    const hasEd25519 = fixturesDirExists && fixtureExists('ed25519');

    (available && hasAttestation && hasEd25519 && clientModule ? it : it.skip)(
      'should create a Node.js attestation referencing a Rust-generated fixture',
      async () => {
        const { attestation, metadata } = readFixture('ed25519');
        const doc = JSON.parse(attestation);

        // Create a new Node.js agent and create an attestation
        // that references the Rust-generated document as its subject
        const client = await clientModule.JacsClient.ephemeral('ring-Ed25519');
        const att = await client.createAttestation({
          subject: {
            type: 'artifact',
            id: metadata.document_id,
            digests: { sha256: doc.jacsSha256 || 'cross-lang-reference' },
          },
          claims: [
            {
              name: 'cross_language_verified',
              value: true,
              confidence: 1.0,
              assuranceLevel: 'verified',
            },
          ],
        });

        expect(att).to.have.property('raw').that.is.a('string');
        expect(att).to.have.property('documentId').that.is.a('string').and.not.empty;
        expect(att.agentId).to.equal(client.agentId);

        const attDoc = JSON.parse(att.raw);
        expect(attDoc).to.have.property('attestation');
        expect(attDoc.attestation.subject.id).to.equal(metadata.document_id);
        expect(attDoc.attestation.claims[0].name).to.equal('cross_language_verified');
      },
    );

    (available && hasAttestation && hasEd25519 && clientModule ? it : it.skip)(
      'should verify a Node.js-created attestation round-trip',
      async () => {
        const client = await clientModule.JacsClient.ephemeral('ring-Ed25519');
        const att = await client.createAttestation({
          subject: {
            type: 'artifact',
            id: 'cross-lang-round-trip',
            digests: { sha256: 'roundtrip123456789' },
          },
          claims: [
            {
              name: 'node_created',
              value: true,
              confidence: 0.99,
              assuranceLevel: 'verified',
            },
          ],
        });

        // Verify locally
        const result = await client.verifyAttestation(att.raw);
        expect(result.valid).to.equal(true);
        expect(result.crypto.signatureValid).to.equal(true);
      },
    );
  });
});
