#!/usr/bin/env python3
"""Render the JACS Homebrew formula only from verified public CLI artifacts."""

from __future__ import annotations

import argparse
import hashlib
import os
import re
import subprocess
import tempfile
from pathlib import Path

try:
    from release_tag import validate_semver
    import verify_github_release_attestations as release
except ModuleNotFoundError:
    from scripts.release_tag import validate_semver
    from scripts import verify_github_release_attestations as release


def render_formula(version: str, checksums: dict[str, str]) -> str:
    validate_semver(version)
    spec = release.release_spec(f"cli/v{version}")
    if set(checksums) != spec.payload_assets:
        raise ValueError("CLI checksums must cover exactly the five released archives")
    if any(re.fullmatch(r"[0-9a-f]{64}", value) is None for value in checksums.values()):
        raise ValueError("invalid CLI archive SHA-256")

    def platform(os_name: str, architecture: str, indent: str) -> str:
        filename = f"jacs-cli-{version}-{os_name}-{architecture}.tar.gz"
        return (
            f'{indent}url "https://github.com/HumanAssisted/JACS/releases/download/'
            f'cli/v{version}/{filename}"\n'
            f'{indent}sha256 "{checksums[filename]}"\n'
        )

    return (
        '# Generated by scripts/homebrew_release.py from attested CLI release assets.\n'
        'class Jacs < Formula\n'
        '  desc "Portable signed JSON and verify-only MCP server"\n'
        '  homepage "https://github.com/HumanAssisted/JACS"\n'
        f'  version "{version}"\n'
        '  license "Apache-2.0"\n\n'
        '  on_macos do\n'
        '    on_arm do\n' + platform('darwin', 'arm64', '      ') +
        '    end\n'
        '    on_intel do\n' + platform('darwin', 'x64', '      ') +
        '    end\n'
        '  end\n\n'
        '  on_linux do\n'
        '    on_arm do\n' + platform('linux', 'arm64', '      ') +
        '    end\n'
        '    on_intel do\n' + platform('linux', 'x64', '      ') +
        '    end\n'
        '  end\n\n'
        '  def install\n'
        '    bin.install "jacs-cli" => "jacs"\n'
        '  end\n\n'
        '  test do\n'
        '    assert_match version.to_s, shell_output("#{bin}/jacs --version")\n'
        '    assert_match "mcp", shell_output("#{bin}/jacs --help")\n'
        '    assert_match "verify-only", shell_output("#{bin}/jacs mcp --help")\n'
        '  end\n'
        'end\n'
    )


def verified_formula(version: str, source_commit: str) -> str:
    validate_semver(version)
    if re.fullmatch(r"[0-9a-f]{40}", source_commit) is None:
        raise ValueError("source commit must be a full reviewed Git commit SHA")
    spec = release.release_spec(f"cli/v{version}")

    def source_bound_run(command: list[str], timeout: int):
        return subprocess.run(
            [*command, "--source-digest", source_commit],
            check=False, text=True, capture_output=True, timeout=timeout,
        )

    assets = release.fetch_complete_release_assets(spec.tag, attempts=1, delay_seconds=0)
    with tempfile.TemporaryDirectory(prefix="jacs-homebrew-verify-") as directory:
        paths = release.download_release_assets(assets, Path(directory))
        release.verify_release_checksums(spec, paths)
        release.verify_attestations(spec, paths, run=source_bound_run)
        checksums = {
            path.name: hashlib.sha256(path.read_bytes()).hexdigest()
            for path in paths if path.name in spec.payload_assets
        }
        return render_formula(version, checksums)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--version", required=True)
    parser.add_argument("--source-commit", required=True)
    parser.add_argument("--output", type=Path, default=Path("Formula/jacs.rb"))
    args = parser.parse_args()
    formula = verified_formula(args.version, args.source_commit)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(mode="w", dir=args.output.parent, delete=False) as stream:
        temporary = Path(stream.name)
        try:
            stream.write(formula)
            stream.flush()
            os.replace(temporary, args.output)
        finally:
            temporary.unlink(missing_ok=True)
    print(f"Wrote {args.output} from verified cli/v{args.version} ({args.source_commit})")


if __name__ == "__main__":
    main()
